apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep1
  template:
    metadata:
      labels:
        app: my-dep1
    spec:
      containers:
        - name: my-container
          image: neksha/se-lab2-web-maven
          ports:
            - containerPort: 8080
            
